### ISSUE TITLE
500 internal server errors

### ISSUE THREAD

**Issue by potchin** [Pushjet/Pushjet-Server-Api#10] opened 2016-08-23 18:55 UTC
Notifications to my android device stopped recently. Doing some troubleshooting as to the cause and it seems api.pushjet.io is returning http 500 errors as soon as my device is registered to receive notifications from that channel.

Example:
- I created a new channel
- sent notifications to it using my python script
- all ok
- I added a subscription to the new channel to my android device using the app
- send same notification and I get a http 500 error

I tried the 'reregister' function in the app but no improvement.

Any ideas?

**Comment by Mechazawa** [comment] 2016-08-23 19:59
I'm currently on a beach.  I think I broke something I didn't test before deploying the latest version. I'll have a look tonight since I'm currently at a beach with 350 Bytes/s wifi so I can't really do anything as of now.
I'm sorry for the inconvenience.

-------- Original message --------From: potchin notifications@github.com Date: 23/08/2016  14:55  (GMT-04:00) To: Pushjet/Pushjet-Server-Api Pushjet-Server-Api@noreply.github.com Subject: [Pushjet/Pushjet-Server-Api] 500 internal server errors (#10) 
Notifications to my android device stopped recently. Doing some troubleshooting as to the cause and it seems api.pushjet.io is returning http 500 errors as soon as my device is registered to receive notifications from that channel.

Example:

I created a new channel
sent notifications to it using my python script
all ok
I added a subscription to the new channel to my android device using the app
send same notification and I get a http 500 error

I tried the 'reregister' function in the app but no improvement.

Any ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Pushjet/Pushjet-Server-Api","title":"Pushjet/Pushjet-Server-Api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Pushjet/Pushjet-Server-Api"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"500 internal server errors (#10)"}],"action":{"name":"View Issue","url":"https://github.com/Pushjet/Pushjet-Server-Api/issues/10"}}}

**Comment by potchin** [comment] 2016-08-23 20:01
No rush, enjoy the beach! Thanks

**Comment by Mechazawa** [comment] 2016-08-25 07:34
The issue should be fixed with dae274118653be18e425e54937780cefad86bc68...b65db5b92ebeb856ef2de56071951597792317e8

**Comment by Mechazawa** [comment] 2016-08-25 07:42
Can you please confirm the bug has been fixed?

**Comment by potchin** [comment] 2016-08-25 08:03
Yep, looks good now. Thanks

**Comment by Mechazawa** [comment] 2016-08-25 08:09
thanks

**Closed as completed by Mechazawa** 2016-08-25 08:09 UTC
Labels: bug

**Comment by AJOnlineServices** [comment] 2018-02-28 22:41
Exact same bug seems to have appeared again. I'm not using the self hosted version, I am using the api.pushjet.io server
